markdown: rdiscount
highlighter: pygments
permalink: /posts/:title.html
rdiscount:
  extensions: [smart]

title: Thomas's Blog
author:
  name: Thomas Liu
  email: liuheng0204@gmail.com
  github: liuheng

production_url: https://liuheng.github.io

baseurl: /
